name: dart_sql
description: A declarative SQL front end for moor:ffi that enables you to construct SQL queries using Dart syntax.
version: 0.0.1
author: Aeyrium <build@aeyrium.com>
homepage: http://aeyrium.com

environment:
  sdk: ">=2.5.0 <3.0.0"

dev_dependencies:
  test: ^1.6.0
